### ISSUE TITLE
No attribute Error

### ISSUE THREAD

**Issue by littleday** [vmagamedov/grpclib#102]
server = Server([MyServicer(conf=config, logger=logger)])
  File "/opt/app-root/lib/python3.6/site-packages/grpclib/server.py", line 569, in __init__
    mapping.update(handler.__mapping__())
AttributeError: 'MyServicer' object has no attribute '__mapping__'

**Comment by vmagamedov** [comment]
What is `MyServicer`? Are you trying to use `grpcio` stubs (`*_pb2_grpc.py`) with a `grpclib` Server?
