### ISSUE TITLE
Failed to generate special stub files.

### ISSUE THREAD

**Issue by devrivne** [vmagamedov/grpclib#103]
I do have a working project that I wanted to run with your implementation.
Got next error on startup:
`  File "/usr/local/lib/python3.7/site-packages/grpclib/server.py", line 569, in __init__
    mapping.update(handler.__mapping__())
AttributeError: 'TestServicer' object has no attribute '__mapping__'
` 
Who should generate file with mapping?

**Comment by vmagamedov** [comment]
`grpclib` and `grpcio` are not interchangeable implementations. Please read [README](https://github.com/vmagamedov/grpclib#id5) to generate appropriate stubs and use them to implement your server-side handlers (servicer).

**Comment by devrivne** [comment]
Hey!
I did every thing from doc

In order to use this library you will have to generate special stub files
using plugin provided, which can be used like this:

$ python3 -m grpc_tools.protoc -I. --python_out=. --python_grpc_out=.
helloworld/helloworld.proto

This command will generate helloworld_pb2.py and helloworld_grpc.py files.

Does not generate files with mapping.

чт, 23 янв. 2020 г. в 18:11, Vladimir Magamedov <notifications@github.com>:

**Comment by arseniybanayev** [comment]
I'm having the same issue, actually. I used the plugin that supports the `--python_grpc_out` parameter as written in README. It generates a model_grpc.py and a model_pb2.py. But when I try to use one of the stubs and create a server with it, I get the same exception as @devrivne.

**Comment by vmagamedov** [comment]
@arseniybanayev take a look at the `model_grpc.py` file, there you should see a class with a `def __mapping__(self)` method. You have to subclass this class and pass it's instance to the `grpclib.server.Server`. Is this what you're doing?

**Comment by arseniybanayev** [comment]
Thx @vmagamedov, your answer is right - I was not clear on how the `Stub` and `Base` files worked. I was working on trying to convert the [python chatbot for Tinode](https://github.com/tinode/chat/blob/master/chatbot/python/chatbot.py) to asyncio using your grpclib library, and I just pieced everything together. Thank you for the wonderful library, it works!

**Comment by vmagamedov** [comment]
Fixed in 210ae2d55a91616afd6da1bc7bcdd223dd0b114c by introducing `--python_grpclib_out=` option and `_grpclib.py` file extension to avoid any misunderstanding
