### ISSUE TITLE
*_grpc.py not generated when installed via poetry

### ISSUE THREAD

**Issue by seanaye** [vmagamedov/grpclib#111]
I'm updating a project that used to use this repo and I haven't changed any code but not when I try to run the project I get 

```
File "./rpc_pb2_grpc.py", line 34, in __init__
self.WalletBalance = channel.unary_unary(
AttributeError: 'Channel' object has no attribute 'unary_unary'
```

relevant code 

```python
import rpc_pb2 as ln
import rpc_pb2_grpc as lnrpc
from grpclib.Client import Channel
...
self._channel = Channel('lnd', 9000, ssl=ctx)
...
self.stub = lnrpc.LightningStub(self._channel)
```
Not sure what is wrong here. rpc_pb2_grpc was compiled as follows

`python -m grpc_tools.protoc --proto_path=googleapis:. --python_out=./build, --grpc_python_out=./build rpc.proto`

where rpc.proto is from https://raw.githubusercontent.com/lightningnetwork/lnd/master/lnrpc/rpc.proto

Appreciate any help.

Thanks.

**Comment by seanaye** [comment]
I think this has to do with the grpclib plugin not being recognized by the compiler. Part of the refactoring that caused this error was the switch from pip to poetry.

I'm not sure how the plugin is installed to the PATH or how to change install location. I'm inexperienced with grpc compilers.

I'm installing inside Docker container with

`RUN poetry config virtualenvs.create false && poetry install`

grpclib is in poetry pyproject.toml

**Comment by vmagamedov** [comment]
`*_pb2_grpc.py` files are generated for `grpcio` package, not for `grpclib`.

`grpclib` generates `*_grpc.py` files with `--python_grpc_out=` option.

In the last release candidate I changed this, because this is not the first time people are confused. I have to document these changes and issue a proper release.

**Comment by seanaye** [comment]
@vmagamedov oh yes I think I remember that from the last time I worked with your library, which is very helpful by the way thank you. 

My issue is that the *_grpc.py file is no longer being generated. I believe this has to do with the way grpclib is installed via poetry. Before, when I was using pip, this file was generated but after switching to poetry it isnt. The only files generated are *_pb2.py and *_pb2_grpc.py.

**Comment by vmagamedov** [comment]
You say that you're generating stubs with `--grpc_python_out=./build` option, but in order to use `grpclib` you have to use `--python_grpc_out=./build` option.

If there is something wrong with `grcplib` installation, you get errors from `protoc`. Are there any errors?

**Comment by seanaye** [comment]
Wow can't believe I missed that sorry.

**Comment by vmagamedov** [comment]
No problem, as I said this is my fault (naming)
