### ISSUE TITLE
Allow infinite pings

### ISSUE THREAD

**Issue by tamirOK** [vmagamedov/grpclib#116]
Hi!

I want my client to hold open connection to server infinitely long by doing pings. To do so, I have to provide correct values for `Configuration` object. Can you answer my questions please:

- What is a difference between `_keepalive_time` and `http2_min_sent_ping_interval_without_data` settings? I have checked `Connection._ping` method and these options look very similar to me.
- How can I remove limit on max number of sent pings?  
- Can I allow ping function to run forever?

Thanks!

**Comment by tamirOK** [comment]
I have read the definitions of the options [here](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) and I think there are couple of problems in the implementation:

- `Connection` is always closed after `_keepalive_timeout` seconds, but it should close only when it didn't received an acknowledgement.
-  `GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA` is allowed to be 0. However, I am receiving:
``` ValueError: "_http2_max_pings_without_data" should be positive ```

**Comment by vmagamedov** [comment]
> Connection is always closed after _keepalive_timeout seconds, but it should close only when it didn't received an acknowledgement.

– `_keepalive_timeout` is cancelled when we receive PING acknowledgment.

> GRPC_ARG_HTTP2_MAX_PINGS_WITHOUT_DATA is allowed to be 0

– fixed

> _http2_min_sent_ping_interval_without_data should not affect client side.

– please elaborate

**Comment by vmagamedov** [comment]
Please take in mind that non-default keep-alive settings can cause PING strikes as described in https://github.com/grpc/grpc/blob/master/doc/keepalive.md, currently this will cause a cancellation of all in-flight requests (`h2` library doesn't handle `GOAWAY` frame correctly).

**Comment by vmagamedov** [comment]
This issue was closed unintentionally, please reopen it if current keep-alive implementation still doesn't conforms to the reference documentation.

**Comment by tamirOK** [comment]
Can I control `GRPC_ARG_HTTP2_MAX_PING_STRIKES` and `GRPC_ARG_HTTP2_MIN_RECV_PING_INTERVAL_WITHOUT_DATA_MS` for the server? If not, are these values equals to the default values from doc?

**Comment by vmagamedov** [comment]
`grpclib` currently doesn't implements strikes functionality, so it is important only if you're using `grpcio` and other official gRPC implementations on the server-side.
