### ISSUE TITLE
Feature request: before/after request methods

### ISSUE THREAD

**Issue by upcFrost** [vmagamedov/grpclib#118]
Hi,

It'd be really cool to support overridable methods called before and after the request (useful for logging and setting the request context), similar to flask `before_request` decorator. For myself I've implemented those using `functools.partial` wrapped around the handler inside the `__mapping__` call override, but it'd be great to have a standard way of doing it

**Comment by vmagamedov** [comment]
Currently you can override a call or track beginning of a request using [RecvRequest](https://grpclib.readthedocs.io/en/latest/events.html#grpclib.events.RecvRequest) event

**Comment by upcFrost** [comment]
Interesting, thank you, I'll try using it. Though it's a bit painful that events should be mapped to the server and not to the handler class (those are in two different modules)
