### ISSUE TITLE
 ImportError: cannot import name 'PingAcknowledged' from 'h2.events'

### ISSUE THREAD

**Issue by hyzyla** [vmagamedov/grpclib#121]
Version `0.3.2` worked correctly until today. In installed packages h2 has version 4.0, wich was changed yesterday in requirements https://github.com/vmagamedov/grpclib/commit/8d5bb3fb19948473f43f13d98a9c1832d8527048

Expected that released previously library with version 0.3.2 should work as before

**Comment by vmagamedov** [comment]
What do you suggest?

**Comment by upcFrost** [comment]
+1. Actually it was kinda strange. Wasn't the h2 version fixed in the requirements?

**Comment by vmagamedov** [comment]
See #119
