### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by mosquito** [vmagamedov/grpclib#13]
Why the `grpclib` was not released on pypi?

**Comment by vmagamedov** [comment]
Mostly because of low tests coverage (== low quality) and lack of documentation. But I think that currently I can make at least a pre-release just for convenience.

**Comment by vmagamedov** [comment]
I will setup project documentation infrastructure and will make a pre-release shortly.

**Comment by vmagamedov** [comment]
Now you can install `grpclib` like this:
```
pip3 install grpclib==0.1.0rc1
```
Note that I'm restarted project versioning.

I'm also added basic docs configuration and now it is available at http://grpclib.readthedocs.io (all new changes will be documented in the changelog)

**Comment by mosquito** [comment]
Thank you.
