### ISSUE TITLE
Missing code-completion in VSCode

### ISSUE THREAD

**Issue by haf** [vmagamedov/grpclib#137]
When generating with protoc, there's no completion in VSCode:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/193115/128167914-8bc560d2-e059-4856-be48-9507781ccdd4.png">

Any idea on how to enable it?

**Comment by vmagamedov** [comment]
Are you aware of [mypy-protobuf](https://github.com/dropbox/mypy-protobuf) project and how `*.pyi` files work in Python?

**Comment by haf** [comment]
Thanks, that's the hint I needed! So mypy is static typing for Python that expose the proto DTO:s as types.
