### ISSUE TITLE
Provide samples for more of the protobuf types

### ISSUE THREAD

**Issue by haf** [vmagamedov/grpclib#138]
Right now "hello world" only sets a string. What of collections and structured values?

**Comment by vmagamedov** [comment]
This library assumes that you already know how to use `protobuf` and it's corresponding documentation:
- https://developers.google.com/protocol-buffers/docs/pythontutorial
- https://developers.google.com/protocol-buffers/docs/reference/python-generated
- https://googleapis.dev/python/protobuf/latest/

You can also use global search here on GitHub and find how other projects use `protobuf` with gRPC. GitHub also shows dependant projects, which use `grpclib` in their requirement.
