### ISSUE TITLE
New Release with Fixed DeprecationWarning Filter 

### ISSUE THREAD

**Issue by nikstur** [vmagamedov/grpclib#175]
I maintain grpclib in Nixpkgs and the package is currently [failing to build](https://hydra.nixos.org/build/219048902/nixlog/3) because of the DeprecationWarning issue fixed in ff9d555bb915dc6310bf31b0b9825a16e0762a64

Can you create a new minor or patch release that includes this commit? This would make it easier to fix this version downstream in Nixpgks.

**Comment by vmagamedov** [comment]
Sure. Issued `0.4.4` release.

**Comment by nikstur** [comment]
Awesome! Thank you!
