### ISSUE TITLE
'Channel' object has no attribute 'request'

### ISSUE THREAD

**Issue by RuofengX** [vmagamedov/grpclib#178]
Same issue to https://github.com/grpc/grpc/issues/27817

Issue happens here when I run the space.py:
https://github.com/RuofengX/game.entropy.press/blob/10aad2df8b51bfeb506be4f584e73d8bb29eaf1d/src/workload.py#L21

**Comment by vmagamedov** [comment]
You mix incompatible generated stubs and libraries.

- Use `grpc.aio.Channel` with `service_pb2_grpc.py` stubs generated using `--grpc_python_out` option
- Use `grpclib.client.Channel` with `service_grpc.py` stubs generated using `--grpclib_python_out` option

All these things are not interchangeable, these are two different incompatible projects. They only use the same protobuf messages and the same `protoc` compiler.

**Comment by RuofengX** [comment]
Worked, thanks.
