### ISSUE TITLE
Add support for Python 3.11

### ISSUE THREAD

**Issue by yomach** [vmagamedov/grpclib#179]
Hi,

Python 3.11 has been out there for quite some time, it would be super useful if support for it would be added.

**Comment by vmagamedov** [comment]
Now `grpclib` is tested also with Python 3.11. Do you mean this as Python 3.11 support or something else?

**Comment by yomach** [comment]
Yes!
I think some older version also had issues with python 3.11, but I guess they were solved.
The added tests is perfect.

**Comment by yomach** [comment]
Reopening it with a small addition:
1. Can you please update `setup.cfg` to indicate to pypi that 3.11 is supported?
2. Any estimate as to when a new version will be out?

**Comment by vmagamedov** [comment]
> Any estimate as to when a new version will be out?

When there will be at least one bug fix or improvement. Library can be used with Python 3.11 even if this version isn't mentioned in the supported versions. We have only minimum supported version which is 3.7.

**Comment by yomach** [comment]
Thanks!
