### ISSUE TITLE
Support async generator for <Any>StreamMethod classes

### ISSUE THREAD

**Issue by claws** [vmagamedov/grpclib#18]
The current implementation of the UnaryStreamMethod assumes that it will accumulate all replies before returning. This is not always desirable.

For example, in my use case I have a Unary_Stream method that provides a publisher style interface. The client sends a Unary request to open the channel and then expects to process a never ending stream of updates. In this use case I need to be able to receive and process individual updates as they are received. In this use case an async generator style interface would be preferable.

Something along the lines of:
```python
async for update in stub.UnaryStreamGreeting(request):
    handle_update(update)
```

I can kind of achieve what I want if I modify the ``grpclib.client.py`` code a little to be:
```python
class UnaryStreamMethod(ServiceMethod):

    async def __call__(self, message, *, timeout=None, metadata=None):
        async with self.open(timeout=timeout, metadata=metadata) as stream:
            await stream.send_message(message, end=True)
            # return await _to_list(stream)
            async for reply in stream.recv_message():
                yield reply
```
However this will only work with the more advanced usage such as this:
```python
    async with stub.UnaryStreamGreeting.open() as stream:
        print(f'sending {request.name}')
        await stream.send_message(request, end=True)
        async for response in stream:
            print(f'received: {response.message}')
```
and not with the simpler usage such as this:
```python
responses = await stub.UnaryStreamGreeting(request)
```
which raises:
```python
TypeError: object async_generator can't be used in 'await' expression
```

Perhaps implementing ``__aiter__`` and ``__anext__`` on the UnaryStreamMethod class could provide the appropriate API allowing it to be used as an async generator to yield individual messages.

**Comment by vmagamedov** [comment]
This is very interesting case. I'm was afraid to implement such API. So I'm forcing users to use async context manager in order to perform such advanced usage.

Given your example:
```python
async for update in stub.UnaryStreamGreeting(request):
    handle_update(update)
```
If your function `handle_update` fails in the middle of iteration, `grpclib` won't be able to cleanup resources and properly close this stream. And the number of open streams in http/2 is limited.

By using `.open()` context manager `grpclib` will be able to cancel this stream properly, and server will know this as soon as possible.

**Comment by akhilman** [comment]
aiostream is nice library that provides context manager to close async generators.

**Comment by vmagamedov** [comment]
I agree, but grpclib also provides context manager to close async generator and it is mandatory to use it.
