### ISSUE TITLE
Include tests/ into PyPI upload?

### ISSUE THREAD

**Issue by jas4711** [vmagamedov/grpclib#200]
Hi.  I am working on adding grpclib to Debian, see packaging here:

https://salsa.debian.org/python-team/packages/python-grpclib/

We are using tarballs coming from PyPI and I noticed that you have a complete `tests/` sub-directory available upstream which is not uploaded into PyPI.

What is the status of the self-tests?

What do you think about including them in the PyPI upload?

Thanks,
/Simon

**Comment by vmagamedov** [comment]
Hey.

Tests and other checks require additional dependencies: [requirements/test.txt](https://github.com/vmagamedov/grpclib/blob/master/requirements/test.txt), they also require some code generation before you can run them. This all tightly coupled to the GitHub Actions CI system to run continuously. So I don't think that there is a benefit to include these tests into release packages.

**Comment by jas4711** [comment]
Thank you -- that is indeed a long list of external packages only for testing.  I'll try to incorporate these into the Debian packaging eventually, though, since it is helpful for us to have good test coverage of the packages.
