### ISSUE TITLE
Please add --help and/or man pages for command-line tools

### ISSUE THREAD

**Issue by jas4711** [vmagamedov/grpclib#201]
Hi.

I'm packaging this for Debian, and there is a policy about having man pages for tools.

This package installs the `/usr/bin/protoc-gen-grpclib_python` and `/usr/bin/protoc-gen-python_grpc` tools.

They don't seem to respond to `-h` or `--help`.

Would you consider adding man pages explaining how these tools are to be used?

Or at least implement `--help` so I can use help2man to make man pages automatically.

Thanks,
/Simon

**Comment by vmagamedov** [comment]
Hey. Such executables are not to be executed by users, these are plugins for the `protoc` compiler.

Here you can find more information about plugins: https://protobuf.dev/reference/other/#plugins

> A plugin is just a program which reads a CodeGeneratorRequest protocol buffer from standard input and then writes a CodeGeneratorResponse protocol buffer to standard output.

So such programs don't have options.

https://packages.debian.org/bookworm/all/nanopb/filelist - here is another example of `protoc` plugin - `protoc-gen-nanopb`, and it also don't have a man page.

**Comment by jas4711** [comment]
Thank you, this makes sense -- although maybe these plugins should have gone into /usr/libexec/ somewhere instead, but I suppose the pattern is already established for the `protoc` tool.
