### ISSUE TITLE
Custom grpc status codes support

### ISSUE THREAD

**Issue by hellysmile** [vmagamedov/grpclib#28]
Hello there! Thnx for awesome lib!

Is there any way to provide custom headers map for stub/channel? Cuz right now it raises ValueError for unknown status code

**Comment by hellysmile** [comment]
I am totally agree, that custom codes should not be used, but I can not force third-party services to no use them, especially if they are enterprise/old/etc

**Comment by vmagamedov** [comment]
> Is there any way to provide custom headers map for stub/channel?

I still don't understand this question. Can you explain your use case (server-side behavior) and how you want to handle it on the client-side using grpclib?

Lets assume that grpclib will raise `GRPCError(Status.UNKNOWN, "Unknown error code {code} with message: {message}")` if server returns custom status code. What are you going to do after that? Or what do you want from grpclib instead?

**Comment by vmagamedov** [comment]
Hm, seems like I'm already handled invalid statuses during latest refactoring, so client should raise:
```python
GRPCError(Status.UNKNOWN, 'Invalid grpc-status: "42"')
```

**Comment by hellysmile** [comment]
Hey @vmagamedov , yes, I've missed a bit with this `ValueError` https://github.com/vmagamedov/grpclib/blob/master/grpclib/client.py#L193 

Yes actual exceptions is `GRPCError(Status.UNKNOWN, 'Invalid grpc-status: "42"')` 

But what to do if this error code is not actual error? How to get response?
