### ISSUE TITLE
How to send metadata from server

### ISSUE THREAD

**Issue by ciiiii** [vmagamedov/grpclib#30]
*send_initial_metadata()* can 't pass Metadata object, I think document should be more detailed.

**Comment by vmagamedov** [comment]
Sending custom metadata currently not implemented. Going to implement this soon.

To read metadata on the client:
```python
async with stub.Method.open() as stream:
    await stream.recv_initial_metadata()
    print(stream.initial_metadata)
    ...
    await stream.recv_trailing_metadata()
    print(stream.trailing_metadata)
```
To read metadata on the server:
```python
async def Method(self, stream):
    print(stream.metadata)
    ...
```

**Comment by ciiiii** [comment]
Oh, Thank u very much!

**Comment by vmagamedov** [comment]
@ciiiii now it is possible to send and receive metadata, documentation updated. I'm going to issue new pre-release soon, but it would be helpful if you were able to test this feature even sooner (by using latest revision from the master branch).
