### ISSUE TITLE
 grpc_reflection

### ISSUE THREAD

**Issue by ciiiii** [vmagamedov/grpclib#32]
+ Is there any plan about [grpc-reflection](https://github.com/grpc/grpc/tree/master/src/python/grpcio_reflection/grpc_reflection)?
+ It provides information about publicly-accessible gRPC services on a server, and assists clients at runtime to construct RPC requests and responses without precompiled service information.
+ Or can you provide some advise about migration?Thx.

**Comment by vmagamedov** [comment]
I wish to implement reflection, but can't say when I will have time for this. Currently I don't like that in grpcio-reflection you have to pass `service_names` to `enable_server_reflection `. I want to find a better way.

**Comment by ciiiii** [comment]
Thank for your reply, except for reflection. And I enjoy grplib, it's a elegant framework.

**Comment by vmagamedov** [comment]
Implemented reflection in the master branch, you can see example here:
https://github.com/vmagamedov/grpclib/blob/96ae1a5/example/reflection/server.py
