### ISSUE TITLE
Server side can't know whether the stream is closed from client 

### ISSUE THREAD

**Issue by weidaxu1988** [vmagamedov/grpclib#38]
My client subscribes info from server using the request-streaming rpc. And I found the server keeps sending data via the stream without any error raised when the client was exited.
I tried to print `stream._stream._h2_connection.state_machine.state` on server side after client was closed, but I keep getting `ConnectionState.SERVER_OPEN` which I expect `ConnectionState.CLOSED`.
Any reply helps.

**Comment by vmagamedov** [comment]
Server can know that request was cancelled in several ways:
- stream was cancelled: client sends RST_STREAM frame, server cancels current request – `asyncio.CancelledError` will be raised inside coroutine, which handles this request
- connection was closed: `grpclib.protocol.H2Protocol:connection_lost` will be called by asyncio, then server cancels all request handlers, which handle streams in this connection

I've tried to reproduce your case with slightly modified streaming example and everything works as expected.

It is ok that server can't notice broken connection immediately, this is ok for TCP. Client can close connection inappropriately, network errors can occur. But in proper conditions server should know about closed connection almost immediately.

BTW, which version of grpclib you are using? There is `grpclib==0.2.0rc1` available. Can you provide more information about how to reproduce your case?

**Comment by weidaxu1988** [comment]
Thanks, the replay helps, my problem solved. Turns out I put a try/except in my stream loop, so it never break the loop. And my grpclib==0.1.1 👍.

**Comment by vmagamedov** [comment]
Great!
