### ISSUE TITLE
client side cpu busy 100% when reached max_concurrent_streams

### ISSUE THREAD

**Issue by weidaxu1988** [vmagamedov/grpclib#39]
hi, I'm using grpclib==0.1.1. when the number of my client side streams is larger than max_concurrent_streams, sometime the cpu increases the usage to 100%.

And I found the code in `grpclib/protocol` as following:
```
async def send_request(self, headers, end_stream=False, *, _processor):
        assert self.id is None, self.id
        while True:
            # this is the first thing we should check before even trying to
            # create new stream, because this wait() can be cancelled by timeout
            # and we wouldn't need to create new stream at all
            if not self._connection.write_ready.is_set():
                await self._connection.write_ready.wait()

            if self._connection.outbound_streams_limit.reached():
                await self._connection.outbound_streams_limit.wait()
                # while we were trying to create a new stream, write buffer
                # can became full, so we need to repeat checks from checking
                # if we can write() data
                continue

            # `get_next_available_stream_id()` should be as close to
            # `connection.send_headers()` as possible, without any async
            # interruptions in between, see the docs on the
            # `get_next_available_stream_id()` method
            stream_id = self._h2_connection.get_next_available_stream_id()
            try:
                self._h2_connection.send_headers(stream_id, headers,
                                                 end_stream=end_stream)
            except TooManyStreamsError:
                continue
            else:
                self._connection.outbound_streams_limit.acquire()
                self.id = stream_id
                self.__buffer__ = Buffer(self.id, self._connection,
                                         self._h2_connection, loop=self._loop)
                release_stream = _processor.register(self)
                self._transport.write(self._h2_connection.data_to_send())
                return release_stream
```

the `while True` loop will block synchronized forever until one stream is released.
And I did some tested, `self._connection.outbound_streams_limit.reached()` works ok so the client never blocks, but sometime the it didn't and the client blocks. I will do some more test, see if it is my fault.
Dose there should have a default timeout in order to raise the exception `TooManyStreamsError`?

BTW, How can I set `max_concurrent_streams` on server_side, Thanks?

**Comment by vmagamedov** [comment]
Interesting. In this case, when the number of opened streams is reached to the maximum, we should wait for `self._connection.outbound_streams_limit.wait()`. And I have a test which checks that this approach works: https://github.com/vmagamedov/grpclib/blob/v0.1.1/tests/test_client_stream.py#L109. But it is possible that I'm counting opened streams in a wrong way.

Maybe in general case client should raise `TooManyStreamsError`. Currently I can't find a reference where this behavior was explained. I decided to implement this logic in a more user-friendly way, with ability to wait until the number of opened streams will go down. But maybe this is a wrong decision if timeouts are not in use.

Do you have a timeout set for outgoing requests? If this timeout doesn't work, then probably it is a bug in grpclib.

Currently there is no public API to change `MAX_CONCURRENT_STREAMS` setting on the server-side. But this feature definitely should be implemented. It is 100 by default, is it too small?

**Comment by weidaxu1988** [comment]
I've tried set timeout for opening a stream. The whole stream will break as the timeout I set. But in my case, I'd like to keep my stream alive forever so I removed timeout.

And I didn't find the timeout param in `stream.send_message()`, so I just add a asyncio.wait_for for handling `send_message()`timeout(I think this is where the while loop blocks), but I'm not sure if it works.

Then yes, The default 100 MAX_CONCURRENT_STREAMS is too small for my case, maybe I should change the h2_connection, have no idea yet. Is there any way that I can change the setting?

**Comment by vmagamedov** [comment]
We have timeouts for the whole requests only. You probably should ensure in your code that you don't making unbound number of concurrent requests. Maybe by using `asyncio.Queue`.

Something like this on the server-side
```python
from h2.settings import SettingCodes

async def handler(self, stream):
    ...
    stream._stream._h2_connection.update_settings({
        SettingCodes.MAX_CONCURRENT_STREAMS: 1000,
    })
    stream._stream._transport.write(stream._stream._h2_connection.data_to_send())
    ...
```
should temporarily help you, but this code probably will be broken in the future releases. Will add a proper way to do this in the next release.

Can you confirm that CPU usage is caused by grpclib? Or the cause is in your code?

**Comment by weidaxu1988** [comment]
After a few time 100% CPU usage happened. I use intelliJ IDE's debug mode, and found the grpclib's while loop won't wait for `self._connection.outbound_streams_limit.wait()` so it blocks everything when CPU increases usage to 100%.
I've tried to reappear the problem this afternoon, but it didn't happen yet.
It's my thought(not confirmed) that `StreamsLimit._limit != h2_connection.remote_settings.max_concurrent_streams` or the open stream is not be count appropriately.

**Comment by weidaxu1988** [comment]
It seems like stream.cancel() on client-side will not reduce the open stream count in `StreamsLimit`?

**Comment by vmagamedov** [comment]
According to the spec cancel (RST_STREAM) should make this stream fully closed. Will look deeper into this issue today. I want to reproduce this issue in tests.

**Comment by vmagamedov** [comment]
Now I think that streams counting was a bad idea, I refactored this code and it should be much more reliable. Also issued new release candidate `grpclib==0.2.0rc2`, please try it.
