### ISSUE TITLE
No Python 2.7 support due to dependancy `multidict`.

### ISSUE THREAD

**Issue by denis-trofimov** [vmagamedov/grpclib#4]
If interested, please see comment here. I can not pass installing further now.
https://github.com/aio-libs/multidict/issues/4

**Comment by webknjaz** [comment]
This package itself uses Python3.5+ syntax, like https://github.com/vmagamedov/grpclib/blob/master/grpclib/client.py#L56.

It does not make sense for to pick dependencies supporting Python 2 (which is dieing, btw) ;)

It looks like @vmagamedov should add Trove classifier declaring supported python version + `python_requires` setuptools argument.

**Comment by vmagamedov** [comment]
Updated README.rst and setup.py files (as @webknjaz suggested) to note that at least Python 3.5 is required for using this library.

**Comment by denis-trofimov** [comment]
Thank you, @webknjaz @vmagamedov.
> It does not make sense for to pick dependencies supporting Python 2 (which is dieing, btw) ;)
@webknjaz grammar (which is dying, btw) ;)
