### ISSUE TITLE
Typehinting support?

### ISSUE THREAD

**Issue by LiraNuna** [vmagamedov/grpclib#40]
Is there a way to add an option for the generated code to allow typehints?

**Comment by vmagamedov** [comment]
Type hints are not implemented yet. I'm not very familiar with mypy, and maybe with some help will be able to add this feature.

**Comment by anxolerd** [comment]
@LiraNuna do you mean typehints for protobuf classes?
Those are using dark magic to work properly, but there is a solution to generate stubs for mypy from `.proto` files. Try this project for that: https://github.com/dropbox/mypy-protobuf. For me it worked good enough)

**Comment by vmagamedov** [comment]
I've manually added some minimal type hints in the mypy branch with use of generics, and now I can catch errors like this:
```
$ MYPYPATH=.:example mypy -m helloworld.client --strict
example/helloworld/client.py:14: error: Unexpected keyword argument "name2" for "HelloRequest"
example/helloworld/client.py:15: error: "HelloReply" has no attribute "message2"; maybe "message"?
```

**Comment by vmagamedov** [comment]
`grpclib==0.3.0rc4` and examples now are fully annotated with types and checked by mypy in the strict mode 🎉 Generated code is also annotated with types.
