### ISSUE TITLE
Add argument user_agent to Channel constructor

### ISSUE THREAD

**Issue by sergeyspatar** [vmagamedov/grpclib#47]
It would be nice if `user_agent` could be set in Channel constructor, also allowing passing `None` if we don't want header `user-agent` be present at all.

**Comment by vmagamedov** [comment]
I think that such low-level details should be hidden from users. What you want to accomplish by changing user-agent header?

See also: https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
> While the protocol does not require a user-agent to function it is recommended that clients provide a structured user-agent string that provides a basic description of the calling library, version & platform to facilitate issue diagnosis in heterogeneous environments.

I'm going to add even more information into this header soon, and I don't know why anyone would want to omit this header.

If you want to add extra information, to implement distributed tracing as an example, you can use metadata.

**Comment by vmagamedov** [comment]
No response, reopen at will
