### ISSUE TITLE
Limit connections

### ISSUE THREAD

**Issue by TimZaman** [vmagamedov/grpclib#49]
Hello! I couldn't find this in the docs, but for a use-case I have, I want to limit the amount of open connections to 1. How do I go about this? Thanks.

**Comment by vmagamedov** [comment]
Hi! It's simple, 1 Channel == 1 Connection. But before `0.2.1rc1` version it was possible to create multiple connections due to issue #44. It is a good practice to create single Channel once and use it for every request.

**Comment by TimZaman** [comment]
Cool. Do you know how i can set a connected/disconnected callback?

**Comment by vmagamedov** [comment]
Currently this feature is not implemented, Channel reconnects automatically. I'm currently working on interceptors/events feature, so it would be possible to listen for such events. Can you describe your use-case? Why you need these callbacks?

**Comment by TimZaman** [comment]
Simple: I only want to allow a single connection with my service, as 1 first call a 'reset' procedure, followed by 'step' procedure (purpose: reinforcement learning). And what I don't want it someone resetting the state of my service, so I only ever want to allow a single channel to be open.

**Comment by TimZaman** [comment]
In any way, such events is exactly what i'd need.

**Comment by vmagamedov** [comment]
I think that limiting connections is not the right solution and such callbacks wont help. Maybe you need some locking mechanism to ensure that there is only one client making changes in your service. You can implement this lock directly in your service or outside by using redis/memcached.
