### ISSUE TITLE
Client Channels not closing ?

### ISSUE THREAD

**Issue by TimZaman** [vmagamedov/grpclib#50]
It _seems_ that client channels aren't closed.

Eg if i were to do something like:
```py
for _ in range(100):
    channel = Channel(...)
    stub = MyStub(channel)
```
Then it seems my process still had 100 files open, whereas if i add `channel.close()` everything seems fine. I noticed this because i ran into `ulimit` problems, when having a ton of channel switching (intentional).

It's also quite possible that I'm stupid and misusing something but I think the above is valid.

**Comment by vmagamedov** [comment]
Maybe I will add connection closing logic into `Channel.__del__` method soon, but with a warning that connection wasn't closed properly. Proper way to close connection is to call `Channel.close` method.

**Comment by vmagamedov** [comment]
Added `Channel.__del__` method, thank you for opening this issue!
