### ISSUE TITLE
Stream reset by remote party

### ISSUE THREAD

**Issue by nbonnotte** [vmagamedov/grpclib#52]
I get a `StreamTerminatedError` when using a `grpclib` client to call a unary-stream service, but I don't see what's wrong with my client, and I could not find a reference to `StreamTerminatedError` in the `grpclib` documentation.

The client calls the service with this:
```python
    async def fetch_from_source(self):
        ...
        async with stub.GetCategory.open() as stream:
            await stream.send_message(rpc.CategoryRequest())
            async for reply in stream:
                yield ...
```

And here is the traceback I get:
```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<handle_import() done, defined at /srv/src/ui/tasks.py:16> exception=StreamTerminatedError('Stream reset by remote party, error_code: 0')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 310, in recv_message
    self._recv_type)
  File "/usr/local/lib/python3.7/site-packages/grpclib/stream.py", line 10, in recv_message
    meta = await stream.recv_data(5)
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 226, in recv_data
    return await self.__buffer__.read(size)
  File "/usr/local/lib/python3.7/site-packages/grpclib/protocol.py", line 97, in read
    await self._ready_event.wait()
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/src/ui/tasks.py", line 34, in handle_import
    feed_report_id=feed_report_id,
  ...
  File "/srv/src/classifier/modeling/adapters/grpc.py", line 36, in fetch_from_source
    async for reply in stream:
  File "/usr/local/lib/python3.7/site-packages/grpclib/stream.py", line 53, in __anext__
    message = await self.recv_message()
  File "/usr/local/lib/python3.7/site-packages/grpclib/client.py", line 312, in recv_message
    return message
  File "/usr/local/lib/python3.7/site-packages/grpclib/utils.py", line 48, in __exit__
    raise self._error
grpclib.exceptions.StreamTerminatedError: Stream reset by remote party, error_code: 0
```
There is nothing special from the `grpcio` server side either (except maybe it's Python 2.7)
```
class CatalogServicer(catalog_pb2_grpc.CatalogServicer):
    def GetCategory(self, request, context):
        categories = [...]
        for data in categories:
            logger.info("RPC transmit category %s", data["id"])
            yield catalog_types_pb2.Category(...)
            logger.info("RPC transmitted category %s", data["id"])
```
and the logs show nothing.

I guess it comes from [theses lines in `grpclib.protocol`](https://github.com/vmagamedov/grpclib/blob/c38f3074f48755b07b6b16affa14f591d7e051ba/grpclib/protocol.py#L328-L330), which get called from [this other line](https://github.com/vmagamedov/grpclib/blob/c38f3074f48755b07b6b16affa14f591d7e051ba/grpclib/protocol.py#L468) because of a `StreamReset` event. But why?

If I catch and silence the exception, everything seems to work fine.

**Comment by vmagamedov** [comment]
Sure, `StreamTerminatedError` should be documented, however the name of the exception speaks for itself :)

`grpcio` sends `RST_STREAM` frame only in case of some error condition, and I assume that this probably happens because of this line:
```python
await stream.send_message(rpc.CategoryRequest())
```
Outgoing messages stream wasn't properly ended, try to specify `end=True` argument, here is an example: [example/streaming/client.py#L39](https://github.com/vmagamedov/grpclib/blob/master/example/streaming/client.py#L39), and here is corresponding documentation: [grpclib.client.Stream.send_message](https://grpclib.readthedocs.io/en/latest/client.html#grpclib.client.Stream.send_message)

**Comment by vmagamedov** [comment]
Documented `StreamTerminatedError` in 466dad44629e40ca02957c55446a849f1768b422, see https://grpclib.readthedocs.io/en/latest/errors.html#grpclib.exceptions.StreamTerminatedError

**Comment by nbonnotte** [comment]
Thanks! I'm still a bit new to grpc, thank you for your explanation. :smile: 
Adding `end=True` did solved the issue.

Is there a reason why on https://grpclib.readthedocs.io/en/latest/index.html it seems to be unnecessary?
```
class Greeter(GreeterBase):

    async def SayHello(self, stream):
        request = await stream.recv_message()
        message = f'Hello, {request.name}!'
        await stream.send_message(HelloReply(message=message))
```

**Comment by vmagamedov** [comment]
There is a difference between client-side and server-side:
- client sends `headers`, `message`, ..., `message[end=True]`
- server sends `headers`, `message`, ..., `message`, `trailers[end=True]`

On the server-side it is obvious to know when we finished sending messages - it is when we send trailers. On the client-side only your code can say when you finished sending messages (imagine stream-stream method type).

Maybe it would be OK to automatically end unended stream from the client-side when client starts to wait for trailers.

**Comment by nbonnotte** [comment]
Uh, you're right! 

But wouldn't it be possible to have an implicit `end=True` in the case of a client sending a unary request, as in my use case? Because then it can only be
- client sends `headers`, `message[end=True]`

... right?

**Comment by vmagamedov** [comment]
Added special check that will raise `ProtocolError` if outgoing messages stream wasn't properly ended. Currently this is the most consistent behavior for this project.
