### ISSUE TITLE
Documentation on setting custom error codes

### ISSUE THREAD

**Issue by deanott** [vmagamedov/grpclib#53]
Hi, new to `grpc` protocols and I was trying to understand how to set explicit `error_codes` but could not find a reference in the docs.

For example, in `grpc` I could do the following:
```
def GRPCMethod(self, request, context):
    context.set_details("Ouch!")
    context.set_code(grpc.StatusCode.INVALID_ARGUMENT)
    return response
```
How would I do the following in `grpclib`? or what is the best practice for this?

The exact situtation I have is my server code does a check to ensure that a message string has a certain number of characters and if it does not I want to return a `INVALID_ARGUMENT` and a message explaining the reason. 

Thanks

**Comment by vmagamedov** [comment]
Hi! In `grpclib` you can use [grpclib.server.Stream.send_trailing_metadata](https://grpclib.readthedocs.io/en/latest/server.html#grpclib.server.Stream.send_trailing_metadata) method to abort request with custom status and message or you can raise `grpclib.exceptions.GRPCError` (not documented yet).

**Comment by deanott** [comment]
Thanks a bunch for messaging getting back, and that seems to work! :)

**Comment by vmagamedov** [comment]
Let's keep this issue opened while this topic is not documented)
