### ISSUE TITLE
Support gRPC keepalive ping

### ISSUE THREAD

**Issue by edigaryev** [vmagamedov/grpclib#54]
When trying to serve an RPC using grpclib 0.2.1 and receiving connections from clients running gRPC 1.18.0, I get the following exceptions:

```
Fatal error: protocol.data_received() call failed.
protocol: <grpclib.protocol.H2Protocol object at 0x7f799dda4048>
transport: <_SelectorSocketTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "[...]/lib/python3.7/site-packages/grpclib/protocol.py", line 407, in process
    proc = self.processors[event.__class__]
KeyError: <class 'h2.events.PingReceived'>
```

It seems that gRPC [keepalive mechanism](https://github.com/grpc/grpc/blob/master/doc/keepalive.md) that was added last year into gRPC is not fully supported yet.

Also, perhaps there should be a distinction between critical and non-critical protocol extensions, like in [X.509](https://tools.ietf.org/html/rfc5280#section-4.2), but I'm not sure if this is the case for gRPC protocol.

**Comment by vmagamedov** [comment]
Hm, interesting, `PingReceived` event was added only recently in `h2==3.1.0`. Seems like that in the previous `h2` versions ping frames were ignored or automatically handled by `h2.Connection`.

Going to fix this ASAP. In the meantime you can downgrade `h2` version to `3.0.1`.

**Comment by vmagamedov** [comment]
Issued `grpclib==0.2.2rc1` release candidate with a fix

**Comment by vmagamedov** [comment]
PING frame is not an extension, it should be supported right from the box. In `h2==3.0.1` this frame is handled automatically and implicitly, since `h2==3.1.0` it is still handled automatically but explicitly.

**Comment by edigaryev** [comment]
>PING frame is not an extension, it should be supported right from the box.

I see, thanks for the quick fix!
