### ISSUE TITLE
How to keep the client waiting for the server to finish the task

### ISSUE THREAD

**Issue by chaojizhangdaxin** [vmagamedov/grpclib#57]
Why does my server report errors when it processes tasks? Accept the picture uploaded by the client, and the server calls the third party package to identify the picture. Finally, the result of recognition is returned to the client.

**Comment by vmagamedov** [comment]
Can you show how you're using grpclib? We have a client and server examples in this repository, can you compare them with your code and find differences?

**Comment by vmagamedov** [comment]
no response
