### ISSUE TITLE
How to send metadata from client?

### ISSUE THREAD

**Issue by zeyadsalloum** [vmagamedov/grpclib#59]
is there an example of how the client would send metadata?

**Comment by nickpro** [comment]
hey. check snippet below, hope it'll help.
```
stub = UserHandlerStub(channel)
request_metadata = {'auth_token': 'some-strongly-hashed-token'}
await stub.UpdateProfile(UpdateProfileRequest(username='benaffleck', metadata=request_metadata))
```

**Comment by vmagamedov** [comment]
Currently there is a lack of examples and documentation about sending and receiving metadata. Going to fix this soon. Here is what we have for now: [UnaryUnaryMethod.\_\_call\_\_](https://grpclib.readthedocs.io/en/latest/client.html#grpclib.client.UnaryUnaryMethod.__call__)

@nickpro I think that you have a typo in your example :)
```python
await stub.UpdateProfile(UpdateProfileRequest(username='benaffleck'),
                         metadata=request_metadata)
```

**Comment by nickpro** [comment]
@vmagamedov right you, fixed my previous reply, thanks!

**Comment by vmagamedov** [comment]
@zeyadsalloum documented metadata usage here: https://grpclib.readthedocs.io/en/latest/metadata.html

Is it Ok to close this issue?

**Comment by zeyadsalloum** [comment]
yup. Thanks for the updating the docs
