### ISSUE TITLE
How can I determine on the client side that server side is fall

### ISSUE THREAD

**Issue by Valentin-Miroshnichenko** [vmagamedov/grpclib#60]
Hello. I would like to know. How can I determine on the client side that server side is fall (server process was killed). I mean get exception on client side if server side not available?

**Comment by vmagamedov** [comment]
Currently client can detect that server is down only when it tries to call RPC method. Channel reconnects automatically, but if server is down, you get `ConnectionRefusedError`.

**Comment by vmagamedov** [comment]
No response, closing...
