### ISSUE TITLE
Error when creating stub

### ISSUE THREAD

**Issue by sawdiggy** [vmagamedov/grpclib#63]
Every time I try to use the channel generated by this client library, I get the following error

```Exception has occurred: AttributeError
'Channel' object has no attribute 'unary_unary'

All this happens when I attempt to create a client to TF serving

```
    loop = asyncio.get_event_loop()
    channel = Channel('0.0.0.0', 9000, loop=loop)
    stub =  PredictionServiceStub(channel)

**Comment by vmagamedov** [comment]
You definitely trying to use `PredictionServiceStub` generated by `grpcio` from some `*_pb2_grpc.py` file. It is not compatible with `grpclib`, and you have to generate compatible stubs by using `protoc` compiler with `grpclib` plugin.

**Comment by sawdiggy** [comment]
Yup, figured that out, thats why I closed the issue.  Issue is trying to use TF servings precompiled grpc stubs wont work, which is a bit of pain as i have to bring in their entire set of protos to cover all the dependent imports.
