### ISSUE TITLE
Channel does not close

### ISSUE THREAD

**Issue by zeyadsalloum** [vmagamedov/grpclib#68]
This lib is great btw! and I am glad i tried it out. I have a small issue with closing channels though. I can't seem to close the channel at all. I tried calling close() on my object's __del__ and i tried to make my object a context manager and calling close() on __exit__ but i just get an exception that the run loop has closed. 
I can see that the channel gets closed anyways on its __del__ so why not just remove the warning?

**Comment by vmagamedov** [comment]
Thanks! Generally you should not rely on `__del__` methods, they are mostly used for safety reasons. At least `grpclib` considers them that way. So I think that showing warning is Ok. Your object probably shouldn't have a `__del__` method.

> but i just get an exception that the run loop has closed

Probably your object or channel was deleted (`__del__` was called) after loop was closed. It is better to explicitly close all resources before stopping event-loop. [AsyncExitStack](https://docs.python.org/3.7/library/contextlib.html#contextlib.AsyncExitStack) may help you manage all your resources properly.

**Comment by zeyadsalloum** [comment]
unfortunately i am using python 3.6 still so i can't use AsyncExitStack yet. hopefully soon i'll migrate. I did however try making my object a contextmanager and close() in __exit__() but I also got the exception. I don't understand why the run loop would close though before __exit__() would be called

**Comment by zeyadsalloum** [comment]
I can still repro this quite easily.
When I call `channel.close()` the `self._protocol` is None so nothing happens.
and then when my object gets deallocated `channel.__del__()` gets called which creates the warning and closes the connection.

I don't get why the protocol is None when I call close(). do you know if it gets cleared somewhere else?

**Comment by vmagamedov** [comment]
Take a look at the `Channel.__connect__()` method. This is the only place where protocol is created. This happens only when you call any RPC method using this channel. So protocol is created lazily on a first request. And if connection is lost, protocol is recreated in the same place.

It is a user's responsibility to not use channel after closing it. Try placing some debugging prints into `Channel.__connect__()` method to find out who uses channel after you close it. [traceback.print_stack()](https://docs.python.org/3/library/traceback.html#traceback.print_stack) can help you.
