### ISSUE TITLE
How can i generate sync Stub?

### ISSUE THREAD

**Issue by Ehco1996** [vmagamedov/grpclib#76]
i found that `protoc-gen-python_grpc` will be replaced  after install grpclib,

so if i run `python3 -m grpc_tools.protoc -I. --python_out=. -python_grpc_out=. xx.proto`

the generated code is in async way，but i want a sync stub .

In other words, I want to a async grpc server but **sync** client !

so , can you help out ? thanks!

**Comment by vmagamedov** [comment]
Sorry for the confusion, but there are two different options:
- `--grpc_python_out=...` - grpcio sync stubs
- `--python_grpc_out=...` - grpclib async stubs

You can use both of them.

**Comment by Ehco1996** [comment]
oh! thanks 
my mistake ..... not looking carefully
