### ISSUE TITLE
How to handle request cancel exception in server wrapper __exit__?

### ISSUE THREAD

**Issue by XuHaoJun** [vmagamedov/grpclib#79]
grpclib = "=0.3.0rc4"
Exception:
```
Request was cancelled
Traceback (most recent call last):
  File "D:\Users\xuhaojun\Dropbox\projects\openditto\.venv\lib\site-packages\grpclib\server.py", line 399, in request_handler
    await method_func(stream)
  File "D:\Users\xuhaojun\Dropbox\projects\openditto\.venv\lib\site-packages\grpclib\utils.py", line 68, in __exit__
    raise self._error
grpclib.exceptions.StreamTerminatedError: Connection was closed
```
got asyncio.CancelledError when stream task cancel, but where to handle request exception?
Code:
``` python
    # UNARY_STREAM - response streaming RPC
    async def UnaryStreamGreeting(
        self,
        stream: Stream[HelloRequest, HelloReply],
    ) -> None:
        try:
            request = await stream.recv_message()
            assert request is not None
            notificationQueue = asyncio.Queue()
            self._queues[stream] = notificationQueue
            while True:
                notification = await notificationQueue.get()
                await stream.send_message(
                    HelloReply(message=f'Notification: {notification}!'))
        except asyncio.CancelledError:
            pass
        finally:
            del self._queues[stream]
```

**Comment by vmagamedov** [comment]
For what reason you want to handle `CancelledError`? You don't want to see these errors in your logs? Please elaborate.

Currently there is no built-in way to disable these logs, but you can use [Filter](https://docs.python.org/3/library/logging.html#logging.Filter) object to filter such logs.

**Comment by XuHaoJun** [comment]
For server cancel tasks on exit or client disconnected, because i collect streams for broadcast and keep stream connecting  wait for server push notification or monitor something, so need to know request cancel or end.

**Comment by vmagamedov** [comment]
In every case `asyncio.CancelledError` is raised to cancel current request. So you're doing everything right, but you will see these errors in your logs – this is ok, but maybe I need to remove this noise.

In your case simple try..finally clause will be sufficient, you don't have to handle this error.

**Comment by XuHaoJun** [comment]
can i get stream cancelled reason or where to get stream error status?

**Comment by vmagamedov** [comment]
> can i get stream cancelled reason

This is not implemented
> where to get stream error status?

Do you mean http/2 RST_STREAM frame's error code sent from client? – also not implemented

**Comment by XuHaoJun** [comment]
thanks for reply!

**Comment by thmzlt** [comment]
> In your case simple try..finally clause will be sufficient, you don't have to handle this error.

I'm also trying to handle client disconnects on an infinite stream. After reading this thread, my understading is that, since this is an expected case, it shouldn't raise an error at all. Does it make sense?

**Comment by vmagamedov** [comment]
@thmzlt when you serve an infinite stream from the server-side you're awaiting something:
```python
while True:
    notification = await notificationQueue.get()  # here
```
... and there is no way to interrupt this await other than to cancel task.

In grpcio (threads) we don't have ability to cancel current request, the only way to end current request is to periodically check `context.is_active()` or register callback with `context.add_callback()`.

Cancellation is a great feature of asyncio, much better than polling/callbacks. If you don't have to perform cleanup (like `del self._queues[stream]` in example above), there is no need to handle `CancelledError` at all. But in asyncio you should expect that your coroutine can be cancelled and use `asyncio.shield()` when needed.
