### ISSUE TITLE
Assert statement should be avoided in runtime code

### ISSUE THREAD

**Issue by aaliddell** [vmagamedov/grpclib#82]
When running Python with optimisations enabled, `assert` statements are skipped:

>The current code generator emits no code for an assert statement when optimization is requested at compile time
-- https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement

So `assert` statements are fine in test code or for library debugging, but should not be used in the library code for control flow or main type checks etc. Instead, `if` and `raise` should be used to give a proper error message to library users.

For example, the check for the passed proto instance being the correct type would be skipped and also presently raises a rather unhelpful `AssertionError` with no error context, where a `TypeError` would be more useful:

https://github.com/vmagamedov/grpclib/blob/5c1018b2b9446c8c3f105bcd23d0a5668a31c3c2/grpclib/encoding/proto.py#L18

```python3
# e.g. becomes
if not isinstance(message, message_type):
    raise TypeError('Incorrect type {} passed for proto, expected {}'.format(type(message), message_type))
```

**Comment by vmagamedov** [comment]
Thanks! Such TypeError is more user-friendly.

**Comment by aaliddell** [comment]
:+1:

There are still a number of other `assert`s in the non-testing library code besides just that example above though. Some probably fit in the 'debugging' camp, but it might be worth checking them.

A grep for `assert` in the `grpclib` directory gives this:
```
grpclib/events.py:        assert len(kwargs) == len(self.__slots__), self.__slots__
grpclib/events.py:                assert (isinstance(dispatches, type)
grpclib/events.py:                assert dispatches not in dispatch_methods, dispatches
grpclib/client.py:                assert exc_val is not None
grpclib/client.py:            assert reply is not None
grpclib/client.py:            assert reply is not None
grpclib/protocol.py:        assert size >= 0, 'Size can not be negative'
grpclib/protocol.py:        assert chunks_size == size
grpclib/protocol.py:        assert value is None or value >= 0, value
grpclib/protocol.py:        assert self.headers is not None
grpclib/protocol.py:        assert self.trailers is not None
grpclib/protocol.py:        assert self.id is None, self.id
grpclib/protocol.py:        assert self.id is not None
grpclib/protocol.py:        assert stream.id is not None
grpclib/protocol.py:        assert stream.id is not None
grpclib/protocol.py:            assert stream.id is not None
grpclib/stream.py:    assert len(message_bin) == message_len, \
grpclib/testing.py:            assert response.message == 'Hello, Dr. Strange!'
grpclib/testing.py:        assert self._channel._protocol is not None
grpclib/utils.py:        assert task
grpclib/utils.py:    assert method_name is not None
grpclib/health/check.py:            assert self._poll_task is not None
grpclib/health/service.py:        assert request is not None
grpclib/health/service.py:        assert request is not None
```

**Comment by vmagamedov** [comment]
Most of these asserts were added specifically for mypy, to convert `Optional[thing]` into `thing`. Checked all current asserts, seems like all of them are properly placed.

**Comment by aaliddell** [comment]
Ok, thanks!
