### ISSUE TITLE
Reflection not working

### ISSUE THREAD

**Issue by 622michael** [vmagamedov/grpclib#93]
I've been unsuccessful in using ServerReflection. Originally, I thought this was a problem with my implementation. However, I tried the reflection example and I've still had no luck.

**What I'm Doing**

I cloned the repo and ran the reflection example.
`python -m reflection.server`

I used grpc_cli to hit the client using:
`grpc_cli ls --l 127.0.0.1:50051`

Output:
`Received an error when querying services endpoint.
Reflection request not implemented; is the ServerReflection service enabled?`

**Comment by 622michael** [comment]
Perhaps this is a duplicate of #92

**Comment by 622michael** [comment]
Confirmed reverting to 0.2.5 fixed it

**Comment by vmagamedov** [comment]
Fix is released in `grpclib==0.3.1rc2`
